version: '3'
services:
  elasticsearch:
    build: ./docker
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx4g"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es_kibana_nw
  kibana:
    image: kibana:8.10.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - es_kibana_nw
networks:
  es_kibana_nw:
